import Masthead from '@/app/ui/masthead';
import Footer from '@/app/ui/footer';

export default function Page() {
  return (
    <div>
      <main className="flex min-h-screen flex-col items-center justify-top">
        <div className="flex items-center justify-center">
          <Masthead />
        </div>
  
         <div className="m-6 md:m-12 pb-20">
            <h1 className="text-center">Terms of Use</h1>
            <p className="text-center">Effective: September 1, 2024</p>
             <div className="mt-6">
                <p>These Terms of Use apply to your use of Ludd AI software applications and websites (all together, &quot;Services&quot;). These Terms form an agreement between you and Ludd AI. By using our Services, you agree to these Terms.</p> 
                <p>Our <a className="underline" href="/privacy">Privacy Policy</a> explains how we collect and use personal information. Although it does not form part of these Terms, it is an important document that you should read.</p>

                <h2>Who we are</h2>
                <p>Ludd AI is an AI research, development, and subversion endeavor. Our mission is to ensure that artificial general intelligence can laugh at itself.</p>
                <h2>Using our Services</h2>
                <p><b>What you can do.</b> Subject to your compliance with these Terms, you may access and use our Services. In using our Services, you must comply with all applicable laws.</p>
                <p><b>What you cannot do.</b> You may not use our Services for any illegal, harmful, or abusive activity. For example, you may not:</p>
                <ul>
                    <li>Use our Services in a way that infringes, misappropriates or violates anyone&apos;s rights.</li>
                    <li>Attempt to or assist anyone to reverse engineer, decompile or discover the source code or underlying components of our Services, including our models, algorithms, or systems (except to the extent this restriction is prohibited by applicable law).</li>
                </ul>
                <h2>Content</h2>
                <p><b>Your content.</b> You may provide input to the Services (&quot;Input&quot;), and receive output from the Services based on the Input (&quot;Output&quot;). Input and Output are collectively &quot;Content.&quot; You are responsible for Content, including ensuring that it does not violate any applicable law or these Terms. You represent and warrant that you have all rights, licenses, and permissions needed to provide Input to our Services.</p>
                <p><b>Ownership of content.</b> As between you and Ludd AI, and to the extent permitted by applicable law, you (a) retain your ownership rights in Input and (b) own the Output. We hereby assign to you all our right, title, and interest, if any, in and to Output.</p>
                <p><b>Similarity of content.</b> Due to the nature of our Services and artificial intelligence generally, output may not be unique and other users may receive similar output from our Services. Our assignment above does not extend to other users&apos; output or any Third Party Output.</p>
                <p><b>Our use of content.</b> We may use Content to provide, maintain, develop, and improve our Services, comply with applicable law, enforce our terms and policies, and keep our Services safe.</p>
                <h2>Disclaimer of warranties</h2>
                <p>BEFORE USING ANY OF THE SERVICES, PLEASE READ CAREFULLY THE FOLLOWING TERMS AND CONDITIONS OF USE. BY ACCESSING, BROWSING AND/OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY ALL CONSENTS AND DISCLOSURES SET FORTH IN THESE TERMS AND CONDITIONS OF USE, INCLUDING ANY FUTURE MODIFICATIONS TO THE TERMS AND CONDITIONS OF USE, AND ANY RELATED AGREEMENTS, GUIDELINES AND POLICIES (COLLECTIVELY, THE &quot;AGREEMENT&quot;). IF YOU DO NOT CONSENT TO THE AGREEMENT, THEN YOU SHOULD NOT USE OR TAKE ADVANTAGE OF THE SERVICES.</p>
                <p>OUR SERVICES ARE PROVIDED &quot;AS IS.&quot; EXCEPT TO THE EXTENT PROHIBITED BY LAW, WE AND OUR AFFILIATES AND LICENSORS MAKE NO WARRANTIES (EXPRESS, IMPLIED, STATUTORY OR OTHERWISE) WITH RESPECT TO THE SERVICES, AND DISCLAIM ALL WARRANTIES INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, NON-INFRINGEMENT, AND QUIET ENJOYMENT, AND ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR TRADE USAGE. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ACCURATE OR ERROR FREE, OR THAT ANY CONTENT WILL BE SECURE OR NOT LOST OR ALTERED.</p>
                <p>THE WEBSITE AND/OR SERVICES ARE AVAILABLE FOR INDIVIDUALS AGED 13 YEARS OR OLDER. IF A USER IS 13 OR OLDER BUT UNDER THE AGE OF 18, THEN SUCH USER AGREES TO REVIEW THE AGREEMENT WITH HIS OR HER PARENT(S) OR GUARDIAN(S) TO ENSURE THAT BOTH THE USER AND PARENT(S) OR GUARDIAN(S) UNDERSTAND AND CONSENT TO THE AGREEMENT AND THAT THE USER AND HIS OR HER PARENT(S) OR GUARDIAN(S) REVIEW AND ACCEPT THE AGREEMENT ON THE USER&apos;S BEHALF. IF THE READER OF THE AGREEMENT IS A PARENT OR GUARDIAN ENTERING THIS AGREEMENT FOR THE BENEFIT OF A CHILD OVER 14, THEN HE OR SHE AGREES AND ACCEPTS FULL RESPONSIBILITY FOR HIS OR HER CHILD&apos;S USE OF THE WEBSITE AND/OR SERVICES, INCLUDING ALL FINANCIAL CHARGES AND LEGAL LIABILITY THAT SUCH CHILD MAY INCUR.</p>
                <h2>Limitation of liability and damages</h2>
                <p>THE SERVICES AND ANY THIRD-PARTY SOFTWARE, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH LUDD AI ARE PROVIDED &quot;AS IS&quot; AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. LUDD AI, AND ITS SUPPLIERS AND PARTNERS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS.</p>
                <p>LUDD AI AND ITS SUPPLIERS AND PARTNERS DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE WEBSITE, THE SERVICES, AND/OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. MOREOVER, LUDD AI, AND ITS SUPPLIERS AND PARTNERS DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF ANY PERSONAL INFORMATION OR LOCATION INFORMATION OR THE SERVICES IN TERMS OF SECURITY, SAFETY, CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. A USER (AND NOT LUDD AI OR ITS SUPPLIERS OR PARTNERS) ASSUME THE ENTIRE COST OF ANY NECESSARY SERVICING, REPAIR, OR CORRECTION RELATED TO THE SERVICES.</p>
                <p>A USER ACKNOWLEDGES AND AGREES THAT UNDER NO CIRCUMSTANCES, INCLUDING, WITHOUT LIMITATION, NEGLIGENCE, WILL LUDD AI, CONTRACTORS, EMPLOYEES, AGENTS, OR THIRD-PARTY PARTNERS OR SUPPLIERS BE LIABLE TO ANY USER FOR ANY SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, RELIANCE, CONSEQUENTIAL, OR EXEMPLARY DAMAGES RELATED TO OR RESULTING FROM: (A) THE USE, DISCLOSURE, DISPLAY, OR MAINTENANCE OF A USER&apos;S PERSONAL INFORMATION OR LOCATION INFORMATION; (B) A USER&apos;S ABILITY OR INABILITY TO USE THE SERVICES; (C) THE SERVICES GENERALLY, INCLUDING THE MOBILE SERVICES, OR SYSTEMS THAT MAKE THE SERVICES AVAILABLE; OR (D) ANY OTHER INTERACTIONS WITH LUDD AI OR ANY OTHER USER OF THE SERVICES, EVEN IF LUDD AI OR A LUDD AI AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>THIS LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE WEBSITE AND/OR THROUGH THE SERVICES, OR RECEIVED THROUGH ANY LINKS PROVIDED ON OR THROUGH THE WEBSITE AND/OR SERVICES, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED ON THE WEBSITE AND/OR SERVICES, AND/OR RECEIVED THROUGH ANY LINKS PROVIDED ON OR THROUGH THE WEBSITE AND/OR SERVICES.</p>
                <p>THIS LIMITATION SHALL ALSO APPLY, WITHOUT LIMITATION, TO THE COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOST PROFITS, OR LOST DATA. SUCH LIMITATION SHALL FURTHER APPLY WITH RESPECT TO THE PERFORMANCE OR NON-PERFORMANCE OF THE WEBSITE AND/OR SERVICES OR ANY INFORMATION OR MERCHANDISE THAT APPEARS ON, OR IS LINKED OR RELATED IN ANY WAY TO THE WEBSITE AND/OR SERVICES. SUCH LIMITATION SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
                <p>WITHOUT LIMITING THE FOREGOING, UNDER NO CIRCUMSTANCES SHALL LUDD AI BE HELD LIABLE FOR ANY DELAY OR FAILURE IN PERFORMANCE RESULTING DIRECTLY OR INDIRECTLY FROM ACTS OF NATURE, FORCES, OR CAUSES BEYOND ITS REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, INTERNET FAILURES, COMPUTER EQUIPMENT FAILURES, TELECOMMUNICATION EQUIPMENT FAILURES, OTHER EQUIPMENT FAILURES, ELECTRICAL POWER FAILURES, STRIKES, LABOR DISPUTES, RIOTS, INSURRECTIONS, CIVIL DISTURBANCES, SHORTAGES OF LABOR OR MATERIALS, FIRES, FLOODS, STORMS, EXPLOSIONS, ACTS OF GOD, WAR, GOVERNMENTAL ACTIONS, ORDERS OF DOMESTIC OR FOREIGN COURTS OR TRIBUNALS, NON-PERFORMANCE OF THIRD PARTIES, OR LOSS OF OR FLUCTUATIONS IN HEAT, LIGHT, OR AIR CONDITIONING.</p>
                <p>USER FURTHER AGREES THAT THE LIMITATIONS OF LIABILITY SET FORTH ABOVE WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THESE TERMS AND CONDITIONS OF USE, AND WILL APPLY EVEN IF ANY LIMITED REMEDY SPECIFIED HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
                <p>APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, THE EXCLUSIONS, AND LIMITATIONS SET FORTH ABOVE MAY NOT APPLY IN THEIR ENTIRETY TO A SPECIFIC USER. SAID USER, HOWEVER, AGREES THAT LUDD AI&apos;S LIABILITY WILL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
            </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
